apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: in-cluster
    namespace: observability
  project: {{ .Values.argocd.project }}
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 41.9.0
    helm:
      version: v3
      values: |
        grafana:
          additionalDataSources:
          - access: proxy
            isDefault: false
            name: loki
            orgId: 1
            type: loki
            url: http://loki:3100
            version: 1
            chart: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
  - group: monitoring.coreos.com
    kind: ServiceMonitor
    jqPathExpressions:
    - .spec.endpoints[]?.relabelings[]?.action
